name: CI (Typecheck & Lint)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      MAIL_API_KEY: ${{ secrets.MAIL_API_KEY }}
      MAIL_VERIFIED_SENDER: ${{ secrets.MAIL_VERIFIED_SENDER }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      RONIN_TOKEN: ${{ secrets.RONIN_TOKEN }}
      CACHE_TOKEN: "casperiv.dev_rate_limit_cache"
      RESEND_API_TOKEN: ${{ secrets.RESEND_API_TOKEN }}
      PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Linting check
        run: pnpm run lint

      - name: Prettier check
        run: pnpm run prettier:check

      - name: Build app
        run: pnpm run build

      - name: Typecheck app
        run: pnpm run typecheck
